### ISSUE TITLE
Inconsistency of dark/light mode through out the page among features 

### ISSUE THREAD

**Issue by thilakjo** [Ctoic/Lisbook#104]
there needs to be consistency and memory of what mode is selected when switching between features.

**Comment by Ctoic** [comment]
how you will resolve it ? @thilakjo

**Comment by Ctoic** [comment]
Okay go ahead @thilakjo

**Comment by thilakjo** [comment]
sorry i thought i was asked about torrent feature, about the light theme to be consistent i will use local storage option in js, hope that helps (also please add the tags of hacktober fest)
