### ISSUE TITLE
Enable Keyboard Shortcuts for Audiobook Controls

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#109]
Description: Improve accessibility by adding keyboard shortcuts for audiobook controls (e.g., play/pause, skip, volume control).

Tasks:

Implement JavaScript logic to detect keyboard inputs for controlling the audiobook player.
Map keyboard shortcuts to common actions (e.g., spacebar to play/pause, arrow keys to skip, etc.).
Ensure compatibility with all browsers.
Acceptance Criteria:

Users can control the audiobook player using keyboard shortcuts.
The shortcuts are intuitive and work across all browsers.
A help section is added to inform users about the available shortcuts.

**Comment by YakeDev** [comment]
Hey @Ctoic 
I already did it

**Comment by Ctoic** [comment]
okay @YakeDev
