### ISSUE TITLE
improving the key features section with auto type

### ISSUE THREAD

**Issue by shalomrionafernandes** [Ctoic/Lisbook#129]
the key features section can be improved with auto type, which will go back and forth with showing features 

<img width="1286" alt="Screenshot 2024-10-22 at 10 55 17 PM" src="https://github.com/user-attachments/assets/cb083129-92ee-4a1f-8d64-66d8e85027ae">

**Comment by shalomrionafernandes** [comment]
sir, pls assign this to me. will deliver a fantastic work as i have done so far

**Comment by Ctoic** [comment]
Yes sure will assign it to you
