### ISSUE TITLE
Add "Add Friend" Button to Friends Template

### ISSUE THREAD

**Issue by Jayasri2111** [Ctoic/Lisbook#132]
Hi @MohitKambli @manoj9896 @khandelwal20sid @vatsaljain-hub @AdityaBavadekar 

Description:
The friends template in the account page lacks an "Add Friend" button, preventing users from adding new friends.

Expected Behavior:
An "Add Friend" button should be available, allowing users to search and add friends easily.

**Comment by Jayasri2111** [comment]
Me and my teammate @Saiharitha3 will work on this issue. Please assign to us.

**Comment by Ctoic** [comment]
Okay go ahead @Jayasri2111. If you like our project do give our repo a 🌟

**Comment by Saiharitha3** [comment]
Hi @Ctoic 
Could you please assign this to me as well? We are working as a team, and resolving this issue is an essential part of our assignment. Having it officially assigned would greatly help us stay organized and efficiently collaborate to meet our goals. We appreciate your support!

**Comment by Ctoic** [comment]
Go ahead @Saiharitha3

**Comment by Saiharitha3** [comment]
@Ctoic please review PR #149 as the solution for this issue.

**Comment by Ctoic** [comment]
I have reveived your PR, can you please review your changes ?

**Comment by Saiharitha3** [comment]
sure @Ctoic, i will review and get back to you

**Comment by Ctoic** [comment]
Great @Saiharitha3

**Comment by Saiharitha3** [comment]
Issue solved.

**Comment by Ctoic** [comment]
Issue resolved :)
