### ISSUE TITLE
Navbar Updation

### ISSUE THREAD

**Issue by abhipariharr** [Ctoic/Lisbook#19]
![Screenshot 2024-10-04 174234](https://github.com/user-attachments/assets/1b098513-77a2-4ba9-9345-b4f045cd468a)
In the Navbar, i can create the fields that will look attractive and login button with hover effect.

Please assign me this issue.

**Comment by Ctoic** [comment]
Sure I will assign it to u @abhipariharr but if you can add an audio book so i can accept your pull request

**Comment by HKSINGHTHAKUR** [comment]
Hii @Ctoic .
I would Like you to assign me this issue under hactoberfest 2024.
looking forward to do it

**Comment by HKSINGHTHAKUR** [comment]
Hii @abhipariharr .
I would like you to assign me this issue under Hactoberfest 2024.
looking forward to do it

**Comment by Ctoic** [comment]
Go ahead @HKSINGHTHAKUR
