### ISSUE TITLE
Add Bookmarks for Audiobooks

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#30]
Add a feature that allows users to create bookmarks in their audiobooks.
Users should be able to return to a specific time in the audiobook where they left off.

**Comment by khandelwal20sid** [comment]
Will local storage work to implement this?

**Comment by Ctoic** [comment]
Yes @khandelwal20sid it will work perfectly.

**Comment by khandelwal20sid** [comment]
Cool, can you assign this to me :)

**Comment by Ctoic** [comment]
sure @khandelwal20sid  you are doing great 🚀
