### ISSUE TITLE
Improve Mobile Responsiveness

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#31]
Description:

Make the app fully responsive on mobile devices.
Ensure all elements, including the audio player, navigation, and buttons, are well-adapted to smaller screens.
Acceptance Criteria:

Use media queries to improve layout on mobile devices.
Test the app on a variety of screen sizes to ensure it is fully responsive

**Comment by subhamagarrwal** [comment]
kindly let me work on this repo

**Comment by Ctoic** [comment]
Go ahead @subhamagarrwal , Don't forget to star the repo && Happy Coding 😄
