### ISSUE TITLE
Add a Download Audiobook Option

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#33]
Description:

Allow users to download audiobooks directly from the app to their local device.
Add a "Download" button next to each audiobook.
Acceptance Criteria:

Implement a download option that saves the audiobook as an MP3 file.
Ensure the download button is user-friendly and intuitive.

**Comment by IngaleChinmay04** [comment]
I want to give it a try. Can you assign it to me?

**Comment by Ctoic** [comment]
Sure Hacktoberfest is all about trying @IngaleChinmay04 👨🏼‍💻
