### ISSUE TITLE
Add Social Media Sharing Options for Audiobooks

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#34]
Description:

Implement social media sharing buttons to allow users to share their favorite audiobooks with friends on platforms like Twitter, Facebook, and WhatsApp.
Each audiobook should have its own shareable link, directing others to the app.
Acceptance Criteria:

Add sharing icons (Twitter, Facebook, WhatsApp, etc.) next to each audiobook.
Ensure each link directs the user to the specific audiobook within the LisBook app.

**Comment by sujalcharati** [comment]
hey @Ctoic  , can i work on it?

**Comment by Ctoic** [comment]
Sure @sujalcharati go ahead 🚀

**Comment by harshitkumargupta** [comment]
HI @Ctoic Please assign me this

**Comment by Ctoic** [comment]
Go ahead @sujalcharati ⭐ our repo and Happy Coding 😄

**Comment by Samyak137** [comment]
I want to work on that, will you please assign it to me.

**Comment by Ctoic** [comment]
Sure @Samyak137
