### ISSUE TITLE
The toggler between Dark mode and light mode is not working.

### ISSUE THREAD

**Issue by swarupn17** [Ctoic/Lisbook#36]
When i click on the toggle it doesn't work. I can make it responsive.
Please can you assign this task to me.
Thanks!

**Comment by Ctoic** [comment]
Sure @swarupn17 go ahead 🚀 Don''t forget to star repo. More new commers will add their contributions. Happy coding 😄

**Comment by swarupn17** [comment]
Hey @Ctoic I am unable to setup the project and can't find good documentation for it.
Please can you tell me how to setup the project locally ?

**Comment by Ctoic** [comment]
Clone the repo to your local machine and run the index.html

**Comment by Ctoic** [comment]
are you facing the issue still ?

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest. I have already did it for my projects . here is the link https://satishmirjan.github.io/OsLabPrograms/.
