### ISSUE TITLE
Add Keyboard Shortcuts for Audio Controls

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#38]
Description:

Make the app more interactive by adding keyboard shortcuts for controlling audiobook playback (e.g., play, pause, skip).
This will enhance the user experience, especially for power users.
Acceptance Criteria:

Implement shortcuts like "Space" for play/pause, "Arrow Left/Right" for skipping, and "+" and "-" for volume control.
Display a list of shortcuts on the audio player page.
Ensure the shortcuts work across browsers and devices.

**Comment by YakeDev** [comment]
Hi @Ctoic , I am interested in contributing to this. Can you assign this to me?

**Comment by khandelwal20sid** [comment]
Hi @Ctoic, if no one is assigned, I'd like to take up this

**Comment by YakeDev** [comment]
Hi @khandelwal20sid, I did it and it already merged

**Comment by YakeDev** [comment]
https://lisbook.netlify.app/

**Comment by khandelwal20sid** [comment]
Ahh I see, okay!

**Comment by Ctoic** [comment]
Hey @khandelwal20sid @YakeDev already implemented shortcuts.
