### ISSUE TITLE
📱💻 Make the App Fully Responsive for Mobile and Desktop

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#4]
We need to improve the responsiveness of the app, ensuring it provides an optimal experience on both mobile and desktop screens. Currently, certain elements may not display correctly or may require too much scrolling. Your task is to update the app’s layout, ensuring it adapts fluidly to different screen sizes and devices.

Your Task:
Mobile Optimization: Make sure the app works smoothly on small screens (like smartphones). Focus on:
Adjusting layout elements, such as cards, images, and buttons.
Implementing mobile-friendly navigation (e.g., collapsible menus, touch-friendly elements).
Ensuring text is readable without zooming in or excessive scrolling.
Desktop Optimization: The app should look well-structured and professional on larger screens:
Adjust grid layouts, margins, and padding to use the extra screen space effectively.
Ensure that elements don’t look too stretched or compressed.
Consistency: Ensure the design remains consistent across all screen sizes. Avoid major differences between mobile and desktop except where necessary for usability.
Testing: Test the changes on various screen sizes (e.g., mobile, tablet, and desktop) using Chrome DevTools or a similar tool.
Suggested Approach:
Use CSS Flexbox or CSS Grid to make the layout responsive.
Consider implementing media queries to handle different screen sizes.
Optimize images and ensure they resize correctly without losing quality.
Use relative units like %, em, or rem rather than fixed pixel values.
Submission Guidelines:
Fork the repository.
Create a new branch (responsive-layout-improvements).
Update the CSS/JS/HTML files to make the layout responsive.
Open a pull request referencing this issue.
Let’s make this app look amazing on every device! 🌟

**Comment by surajb0710** [comment]
Can you please assign this to me?

**Comment by Ctoic** [comment]
go ahead @surajb0710

**Comment by surajb0710** [comment]
@Ctoic I see a lots of changes has been added for UI improvement, it wont be appropriate to push my changes, since it might introduce new issues. Hence, I unassigned myself from this ticket.

**Comment by Ctoic** [comment]
Sure still I can assign you some good first issues @surajb0710

**Comment by surajb0710** [comment]
Yes, but only front end please.
