### ISSUE TITLE
Improve the Audiobook Listing Page

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#40]
Description:

Make the audiobook listing page more interactive by adding hover effects, animations, and tooltips.
Each audiobook tile should show details like the title, author, and duration on hover.
Acceptance Criteria:

Add hover animations to audiobook tiles.
Display additional information (e.g., author, length) in a tooltip or overlay when hovered.
Ensure the page looks good on both mobile and desktop.

**Comment by AdityaBavadekar** [comment]
Hi @Ctoic , I am interested in contributing to this. Ca you assign this to me?

**Comment by AdityaBavadekar** [comment]
Can I also add currently playing bar like Spotify.

![image](https://github.com/user-attachments/assets/0702ad91-e470-44a3-9088-6b11fd271233)

**Comment by Ctoic** [comment]
Hey @AdityaBavadekar go ahead 🚀 , star the repo and happy coding 😄

**Comment by subhamagarrwal** [comment]
kindly let me work on this repo
would be highly appreciated

**Comment by AdityaBavadekar** [comment]
Hi @Ctoic , I had a question, the AudioList Page is same as the main page right? (Where the Currently selected audio book details are also show)

**Comment by YakeDev** [comment]
> Hi @Ctoic , I had a question, the AudioList Page is same as the main page right? (Where the Currently selected audio book details are also show)

Hi @AdityaBavadekar, I think we have to create a home page with all audio book (like cards); I can work on it

**Comment by Ctoic** [comment]
Sure @YakeDev go ahead you are doing great 🚀

**Comment by AdityaBavadekar** [comment]
![image](https://github.com/user-attachments/assets/0c64205c-9fb5-46dd-82c0-d95e318c34a1)

I had added this. Is this good?

**Comment by YakeDev** [comment]
@AdityaBavadekar let me check, it look amazing

**Comment by AdityaBavadekar** [comment]
https://librivox.org/api/feed/audiobooks/?id=52&format=json

**Comment by YakeDev** [comment]
because there is not 1 audio per book, right?

**Comment by AdityaBavadekar** [comment]
ok right, then this api is not useful

**Comment by YakeDev** [comment]
We have to create the card manually, or we need to have 1 audio per book.
or we have to find another way

**Comment by YakeDev** [comment]
> The project can also use this api: https://librivox.org/api/feed/audiobooks/?id=52&format=json but it does not provide audio files.

can you share with me the html and css of this ? I want to try something if it will work

**Comment by AdityaBavadekar** [comment]
the card will be for a audio book. when it is clicked the page will load sub audios from that book

**Comment by YakeDev** [comment]
Yes, right

**Comment by YakeDev** [comment]
there is not API for audiobook what we can use?
@Ctoic any idea?

**Comment by Ctoic** [comment]
For what purpose you need the API @YakeDev ?

**Comment by YakeDev** [comment]
> For what purpose you need the API @YakeDev ?

to upload dynamically audiobook

**Comment by YakeDev** [comment]
> ok right, then this api is not useful

Audio doesn't play

**Comment by AdityaBavadekar** [comment]
@YakeDev do you mean we dont need to play every audio book, just keep on playing one or two?

**Comment by AdityaBavadekar** [comment]
actually the api also provides a rss link for each book, which contains the audio files:
```
 </item>
    <item>
    <title><![CDATA[1-2 The Apostolical Vocation of Saint Mael]]></title>
    <itunes:episode><![CDATA[2]]></itunes:episode>
    <!--<reader>file element=reader</reader> -->
    <link><![CDATA[https://librivox.org/penguin-island-by-anatole-france/]]></link>
            <enclosure url="https://www.archive.org/download/penguin_island_ms_librivox/penguin_island_02_france_64kb.mp3" length="0" type="audio/mpeg" />
  <itunes:explicit>No</itunes:explicit>
  <itunes:block>No</itunes:block>
  <itunes:duration>
    <![CDATA[00:09:43]]>
  </itunes:duration>
  <!--<pubDate>file element=rss.pubDate</pubDate>-->
  <media:content url="https://www.archive.org/download/penguin_island_ms_librivox/penguin_island_02_france_64kb.mp3" type="audio/mpeg" />
 </item>
    <item>
    <title><![CDATA[1-3 The Temptation of Saint Mael]]></title>
    <itunes:episode><![CDATA[3]]></itunes:episode>
    <!--<reader>file element=reader</reader> -->
    <link><![CDATA[https://librivox.org/penguin-island-by-anatole-france/]]></link>
            <enclosure url="https://www.archive.org/download/penguin_island_ms_librivox/penguin_island_03_france_64kb.mp3" length="0" type="audio/mpeg" />
  <itunes:explicit>No</itunes:explicit>
  <itunes:block>No</itunes:block>
  <itunes:duration>
    <![CDATA[00:06:53]]>
  </itunes:duration>
  <!--<pubDate>file element=rss.pubDate</pubDate>-->
  <media:content url="https://www.archive.org/download/penguin_island_ms_librivox/penguin_island_03_france_64kb.mp3" type="audio/mpeg" />
 </item>
```

**Comment by AdityaBavadekar** [comment]
@Ctoic Can you close this issue since it is dormant?
