### ISSUE TITLE
Enhance Error Handling with Interactive Messages

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#42]
Description:

Improve user experience by adding interactive error messages or popups when something goes wrong (e.g., unable to play audio, file not found, etc.).
Make error messages more descriptive and provide suggestions or troubleshooting steps.
Acceptance Criteria:

Create friendly and clear error messages with suggestions.
Display popups for errors related to audio playback, missing files, or connectivity issues.
Ensure the messages are responsive and styled consistently.

**Comment by khandelwal20sid** [comment]
Hi @Ctoic , I'd like to take up this one

**Comment by Ctoic** [comment]
Go ahead 🚀 don't forget to ⭐ the repo and happy coding 😄
