### ISSUE TITLE
Add a "Share Progress" Button on the Audiobook Player Page

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#44]
Description:

Implement a "Share Progress" button on the audiobook player page that allows users to generate a unique link with the current time in the audiobook.
Users can share the link with friends, and they’ll be able to pick up the audiobook from the same point.
Acceptance Criteria:

Add a "Share Progress" button next to the playback controls.
Generate a unique URL that includes the current playback time.
Ensure the shared link opens the audiobook at the correct timestamp.

**Comment by Tomkndn** [comment]
Basically I have to build a share a progress button which generates a link to the audio at current time stamp and the link is copied to our clipboard right?

**Comment by Ctoic** [comment]
I will merge your pull request @Tomkndn. have you created one ?

**Comment by Ctoic** [comment]
@Tomkndn are u working on it ?

**Comment by Tomkndn** [comment]
> @Tomkndn are u working on it ?

yeah working on it

**Comment by Ctoic** [comment]
ok @Tomkndn great

**Comment by Tomkndn** [comment]
one doubt
I should generate a link that will be displayed somewhere or simply the link will be copied to clipboard.

**Comment by Tomkndn** [comment]
also please suggest the button where to align or color or anything....
![image](https://github.com/user-attachments/assets/ffe83d75-39ae-4dc2-a59d-f32d94a01471)

**Comment by Tomkndn** [comment]
?

**Comment by Ctoic** [comment]
Hey @Tomkndn Go ahead and fetch the latest  code that add your changes

**Comment by Ctoic** [comment]
Add the button with share faviorite and comment Icon below book cover.

**Comment by Tomkndn** [comment]
have a look
![image](https://github.com/user-attachments/assets/b099aa0a-d3dc-442e-ab58-a2b313a6f8cd)

**Comment by Tomkndn** [comment]
is this okay 
should i create PR for this now?

**Comment by Ctoic** [comment]
Yes create one but you should fetch the latest code

**Comment by Tomkndn** [comment]
ok

**Comment by Ctoic** [comment]
@Tomkndn 👍🏼
