### ISSUE TITLE
Add "About" Page with Information on Contributors and Maintainers

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#49]
Description: We want to add an "About" page to the LisBook app. This page will include information about the contributors and maintainers of the repository, giving credit to the people who have contributed to this open-source project. The "About" page should be clean, informative, and styled consistently with the rest of the app.

Tasks:

Create a new "About" page (about.html) in the project.
Add a section with a brief description of the LisBook project and its purpose.
List the contributors and maintainers, including:
Name
Profile picture or avatar (optional)
GitHub username with a link to their profile
Include a link to the "About" page in the navigation bar so users can access it easily.
Style the page using CSS and Bootstrap to match the overall design of the app.
Test the page to ensure it works well on both desktop and mobile.
Acceptance Criteria:

The "About" page is accessible from the navigation bar.
The page contains a brief project description and a section for contributors and maintainers.
Information is well-organized and styled in a visually appealing way.
The page is responsive and works smoothly across devices.

**Comment by YakeDev** [comment]
I'm interested in working on this

**Comment by Ctoic** [comment]
Sure I will assign you but keep the basic theme in mind. Make it as attractive as you can.

**Comment by YakeDev** [comment]
> Sure I will assign you but keep the basic theme in mind. Make it as attractive as you can.

Should I use a makdown file or do it directly with html ? or it is up to me?

**Comment by Ctoic** [comment]
It is upto you, I want a list of contributors on our current application. You can use html and add some cool animations with bootsrap and js

**Comment by Ctoic** [comment]
Hey @YakeDev if you get time we can arrange a meeting to discuss further about the future features of lisbook ? I really appreciate your efforts.

**Comment by YakeDev** [comment]
Hey @Ctoic Thanks a lot, no problem

**Comment by Ctoic** [comment]
Yeah if we get time we can discuss what new functionalities we can add and how we can improve overall UI.

**Comment by Ctoic** [comment]
You can also raise some issues @YakeDev which we can discuss.

**Comment by YakeDev** [comment]
> You can also raise some issues @YakeDev which we can discuss.

D'accord, pouvez-vous faire en sorte que ceux qui ajouter des fonctionnalites ne modifie pas le UI, comme ca nous pouvons avancer rapidement, une fois que je finis a harmoniser toutes les pages, on pourra parler des autres amelioration.

je ne sais si cale vous convient

**Comment by Ctoic** [comment]
Sure i will not merge other code unless we are done with the overall design.

**Comment by Ctoic** [comment]
@YakeDev

**Comment by YakeDev** [comment]
@Ctoic

**Comment by YakeDev** [comment]
> new functionalities
Hey @Ctoic 
Can talk about this?

**Comment by Ctoic** [comment]
Yes sure

**Comment by Ctoic** [comment]
Are you available @YakeDev ?

**Comment by Ctoic** [comment]
We can shedule a meeting if you are free ?

**Comment by YakeDev** [comment]
My English is broken, I'm always speaks french, but we can

**Comment by YakeDev** [comment]
@Ctoic 
I'm free in 5 hours, at 6 PM Lubumbashi time.

**Comment by Ctoic** [comment]
Sure nno worries we can use any LLm it will be our translator Don't worry about it @YakeDev

**Comment by Ctoic** [comment]
Okay that's great. I will share a google meet link on your linkedin.

**Comment by YakeDev** [comment]
Okay, Thanks

**Comment by YakeDev** [comment]
> Sure nno worries we can use any LLm it will be our translator Don't worry about it @YakeDev

I Like to speak in english to improve, It is a good way

**Comment by Ctoic** [comment]
I was looking at the logo issue, actually I'm dealing couple of other projects as well tha's why I'm taking more time to reposnd to issues. I think i should merge your request then we can debug it with time ? what do you say @YakeDev

**Comment by Ctoic** [comment]
Then should I merge your request ? @YakeDev we can solve the bug later ?

**Comment by Ctoic** [comment]
Sure @YakeDev I will merge your request.
