### ISSUE TITLE
🎨 Add a New Theme to LisBook

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#5]
LisBook allows users to change the theme, but we want to add more options! Your task is to create and add a new theme (color scheme) for the player.

Steps:
Fork the repository.
Create a new branch: add-new-theme.
Add a new CSS file with the theme's color scheme (you can modify the existing one or create a completely new look).
Update the theme selection dropdown to include your new theme.
Submit a pull request.
Example:
Dark mode, light mode, or even a funky neon theme—the choice is yours!

**Comment by Vedantjn** [comment]
Hey, I would love to implement this, kindly assign it to me.

**Comment by Ctoic** [comment]
Sure @Vedantjn go ahead. Happy Coding :)

**Comment by Vedantjn** [comment]
@Ctoic , kindly update the topic: 
![image](https://github.com/user-attachments/assets/7322f898-af8a-4963-acb5-4abcd2af03a0)

**Comment by Ctoic** [comment]
kindly check the labels and lemme know

**Comment by Vedantjn** [comment]
Great, it is correct now.
