### ISSUE TITLE
Add LisBook Logo to the Navbar

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#51]
Description: We want to improve the visual appeal of the LisBook app by adding a logo to the navigation bar. This will enhance the branding of the app and make it more recognizable. The logo should be placed on the left side of the navbar, and it should be responsive, scaling properly on both desktop and mobile screens.

Tasks:

Design or select an appropriate logo for LisBook.
Add the logo image to the project’s assets folder (e.g., /images/logo.png).
Modify the HTML and CSS to display the logo on the left side of the navbar.
Ensure the logo links back to the homepage (index.html).
Test that the logo displays correctly on both desktop and mobile views.
Ensure the logo scales properly on different screen sizes using responsive design.
Acceptance Criteria:

The logo is visible on the left side of the navbar.
The logo links back to the homepage (index.html).
The logo is responsive and scales well on both desktop and mobile devices.
The logo does not interfere with the existing navigation items.
Changes are documented in the README file.

[Lisbook logo](https://www.canva.com/design/DAGSTstWiS0/NwVcar5HnBvglJcZ3Rewyg/edit?utm_content=DAGSTstWiS0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by n-keerthi-gayathri** [comment]
@Ctoic assign me

**Comment by Sujal942** [comment]
Hey Can I work in this can you please assign it to me.

**Comment by Ctoic** [comment]
@n-keerthi-gayathri are you working on it ? If not then I will assign this to @Sujal942 ?

**Comment by n-keerthi-gayathri** [comment]
> @n-keerthi-gayathri are you working on it ? If not then I will assign this to @Sujal942 ?

yes i am working on it.
and one more thing shall i use this logo??
![image](https://github.com/user-attachments/assets/d9f7c080-9419-4806-90f5-875b5c8ef683)

**Comment by Ctoic** [comment]
@n-keerthi-gayathri Yes this logo but it should be consistent with overall design.

**Comment by Samyak137** [comment]
I want to work on that, will you please assign it to me.
