### ISSUE TITLE
Add a “Recently Played” Section

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#57]
Description: Allow users to quickly access audiobooks they recently listened to by creating a "Recently Played" section below the "Top Audio Books" section.
Tasks:
Use localStorage to store the last few audiobooks the user played.
Create a new section on the homepage to display these books.
Ensure it updates dynamically as users interact with new books.

**Comment by G-SaiVishwas** [comment]
Hello! @Ctoic 

I am a git beginner and I am eager to learn and grow with the help of such wonderful projects. Please assign me this particular task for Hacktoberfest 2024. Really looking forward to contribute.

Thank you!

**Comment by Ctoic** [comment]
Sure @G-SaiVishwas I'm here to help those who are new to Git and Githtub. Go ahead I wish you good luck 🤞🏼 and Don't forget to ⭐ the repo. Happy Coding 😄

**Comment by G-SaiVishwas** [comment]
@Ctoic 
I am done with it and I have generated a pull request. Please check the code and merge it. 
Thank you!
