### ISSUE TITLE
🎧 Add a Play/Pause Button Icon Animation

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#6]
Let’s make LisBook more interactive by animating the play/pause button. When users click the button, it should smoothly transition between the play and pause icons.

Steps:
Fork the repository.
Create a new branch: add-button-animation.
Modify the play/pause button to include an animation that transitions between the play and pause states.
Use CSS or JavaScript to create a smooth animation (for example, a rotating or fading effect).
Submit a pull request.
Example:
You could use an icon that spins or changes color when transitioning between play and pause.

**Comment by VaradJadhav** [comment]
hey @Ctoic  please assign me this issue!

**Comment by harshitkumargupta** [comment]
Hey, please assign this issue to me

**Comment by Ctoic** [comment]
And if you want add your faviorte book as well. In this way we will create a free book app with thousand of books. Happy Coding

**Comment by harshitkumargupta** [comment]
Hi @Ctoic 
Please give under the hacktoberfest tag

**Comment by HKSINGHTHAKUR** [comment]
Hii @Ctoic 
I kindly request you to assign me this issue under Hactoberfest 2024.
looking forward to do it. 
this is my first hactobest challenge. plzz assign me this under with tag
