### ISSUE TITLE
Improve in Book Image Size

### ISSUE THREAD

**Issue by Sujal942** [Ctoic/Lisbook#66]
In this the Book image is not fit properly to container and not cover it look like this.

Before 
![Screenshot 2024-10-13 143832](https://github.com/user-attachments/assets/08675fb3-319f-4107-9dea-2ba2f48786c5)
After Change it look like this
![Screenshot 2024-10-13 144441](https://github.com/user-attachments/assets/91880ea0-4962-4126-b4a5-d388afe615f5)

**Comment by Ctoic** [comment]
Sure @Sujal942 and can you do this for the remaining pages ?

**Comment by Sujal942** [comment]
ok Sure but 2,3,4 pages also need to be improve specially 4 page all the items are not align properly.

**Comment by Ctoic** [comment]
Someone messed the code up will fix it soon, reviewer didn't reveied the code properly.

**Comment by HKSINGHTHAKUR** [comment]
Hii @Sujal942  @Ctoic 
I would like you to assign me this issue under hactoberfest 2024.
looking forward to do it.

**Comment by dakshh-bhardwaj** [comment]
Heyy @Ctoic can you please assign me this issue?

**Comment by Ctoic** [comment]
This issue is also done @dakshh-bhardwaj

**Comment by Sujal942** [comment]
@Ctoic book image is not display properly.
