### ISSUE TITLE
Fix Layout and Functionality of Pages 2, 3, and 4

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#67]
Description:
Pages 2, 3, and 4 of the LisBook application need attention in terms of layout and functionality to ensure a consistent and user-friendly experience. The current design and implementation may cause issues on different screen sizes, and some elements might not be functioning as expected.

Steps to Reproduce:
Navigate to Pages 2, 3, and 4.
Check for layout inconsistencies (misaligned elements, overlapping content, etc.).
Verify that all interactive elements (buttons, links, etc.) are working as expected.
Inspect on both mobile and desktop to ensure responsiveness.
Tasks to be Done:
 Review and fix any layout issues (misalignment, missing margins/padding, etc.).
 Ensure that buttons and links on the pages are functional.
 Add responsive CSS to improve the mobile experience.
 Use Bootstrap components to ensure consistency with the rest of the site.
 Cross-check browser compatibility and adjust where necessary.
 Add consistent headers and footers (same across all pages).
Expected Outcome:
Pages 2, 3, and 4 should have a polished and consistent layout.
All interactive elements should work smoothly across all devices (mobile, tablet, and desktop).
The design should match the rest of the LisBook application, following the theme and responsiveness.

**Comment by YakeDev** [comment]
Hey @Ctoic, Assign me this also, pls

**Comment by manoj9896** [comment]
@ctoic would like to work on this issue 
Sharing the changes in mobile and web view here

![Screenshot 2024-10-13 at 6 31 06 PM](https://github.com/user-attachments/assets/322ec090-797a-4644-a8fd-2da060964d38)
![Screenshot 2024-10-13 at 6 40 52 PM](https://github.com/user-attachments/assets/cefc7fca-a725-49ce-97ff-68ff56e8bf78)

**Comment by YakeDev** [comment]
okay

**Comment by YakeDev** [comment]
> @Ctoic would like to work on this issue Sharing the changes in mobile and web view here
> 
> ![Screenshot 2024-10-13 at 6 31 06 PM](https://private-user-images.githubusercontent.com/51627080/376037131-322ec090-797a-4644-a8fd-2da060964d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjUzOTMsIm5iZiI6MTcyODgyNTA5MywicGF0aCI6Ii81MTYyNzA4MC8zNzYwMzcxMzEtMzIyZWMwOTAtNzk3YS00NjQ0LWE4ZmQtMmRhMDYwOTY0ZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEzMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhY2NjYjhkZThhZGYyYmI4NWEzYWNiZDUwNGQwODRlYzdhOTFhMDJiNTFlNzJjZTVkZmU4NmViZDVjYjg4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QmfO_O5oRFJzD61EE9mxJU3RZxLQiPfakcDXM-LMoJM) ![Screenshot 2024-10-13 at 6 40 52 PM](https://private-user-images.githubusercontent.com/51627080/376037134-cefc7fca-a725-49ce-97ff-68ff56e8bf78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjUzOTMsIm5iZiI6MTcyODgyNTA5MywicGF0aCI6Ii81MTYyNzA4MC8zNzYwMzcxMzQtY2VmYzdmY2EtYTcyNS00OWNlLTk3ZmYtNjhmZjU2ZThiZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEzMTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNWNhOWQ3MGEzMTlhMGEwODAzYjJkMjljZDIwNGFhODM0OWI3YzkxODMwYTIxMDQ4MjcyOGZmZjM0ZjA4ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9vg3GI3wSG5mPwy6Yv7mpHuSlxwlDezoYzN1MXI7PE)

![image](https://github.com/user-attachments/assets/77256690-8d3f-4cdd-af95-63d636f5ab60)

**Comment by manoj9896** [comment]
@YakeDev
Your changes look great.
You can work on this issue I will pick some other issue

**Comment by YakeDev** [comment]
@Ctoic 
okay

**Comment by Ctoic** [comment]
@manoj9896 thank you for your time. You can look for other issues or you can propose some new changes will assign the issue to you

**Comment by Ctoic** [comment]
@YakeDev 👍🏼

**Comment by Sujal942** [comment]
Hey @Ctoic  i already make change and can i rise a PR for this will you assign it to me.

**Comment by Ctoic** [comment]
can you share some sanpshots of your work ? @manoj9896
