### ISSUE TITLE
Add Animations to Page Transitions

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#68]
Description: Implement subtle animations between page transitions to make the app feel more interactive and responsive.
Tasks:
Use CSS transitions or JavaScript to animate page transitions.
Ensure the animations are not too intrusive and load smoothly on different devices.

**Comment by harshitkumargupta** [comment]
HI @Ctoic Can you please assign me this.

**Comment by Ctoic** [comment]
Hey @harshitkumargupta go ahead

**Comment by Ctoic** [comment]
But Keep it in mind the code changes so frequently because alot of students are contributing so fetch the latest changes before pushing your code to main branch.

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest. Thanks!
