### ISSUE TITLE
🎨 Issue #1: Add Dark Mode Theme to LisBook

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#7]
We want to offer users the option to switch between light and dark themes. Your task is to implement a dark mode feature that can be toggled via a button in the app.

Steps to Follow:
Add a toggle button for switching between light and dark themes.
Define CSS classes for both themes.
Implement JavaScript logic to switch between the themes.
Ensure the selected theme persists even after page reloads (use localStorage or sessionStorage).
Test the responsiveness of the new theme on both desktop and mobile.

**Comment by VaradJadhav** [comment]
hey @Ctoic  please assign me this issue!

**Comment by Ctoic** [comment]
Go Ahead @VaradJadhav

**Comment by Sanikar12** [comment]
@Ctoic , can u assign this issue to me ?

**Comment by Ctoic** [comment]
sure will assign to you but you have to implement the same functionality in the second page and last page

**Comment by HKSINGHTHAKUR** [comment]
Hii @ctoic.
I kindly request you to assign me this issue under my first hactoberfest 2024.
looking forward to do it
