### ISSUE TITLE
Add Loader Animation During Page Load

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#70]
Description: Add a loading spinner or animation while the page content is being fetched, especially when loading the audio files or large book data.
Tasks:
Design a simple and modern loading animation using CSS or JavaScript.
Display the loader while content is loading, especially on slower connections.
Ensure the loader disappears smoothly once content is ready.

**Comment by 2MJ-DEV** [comment]
I'll take care of it, assign me the task

**Comment by Ctoic** [comment]
sure @2MJ-DEV go ahead 👍🏼

**Comment by Satishmirjan** [comment]
Hi, could you please assign this issue to me? I'd love to contribute as part of Hacktoberfest. Thanks!

**Comment by 2MJ-DEV** [comment]
@Ctoic I have already updated the feature but it has not been taken into account yet!!
