### ISSUE TITLE
 Improve Chapter/Part Listing UI

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#71]
Description: The current list of book chapters/parts appears basic. The design could be enhanced to make it more interactive and visually engaging.
Tasks:
Redesign the chapter list, giving each part a distinct card style or button-like design.
Add hover effects to each chapter/part.
Make the current playing chapter more prominent (change background, add a playing indicator).

**Comment by Ctoic** [comment]
![Screenshot from 2024-10-13 16-24-56](https://github.com/user-attachments/assets/205fff66-0a04-4b8f-a816-5526103c488c)

**Comment by YakeDev** [comment]
I'm working on, assign me this UI task
![Uploading home page test.png…]()

**Comment by Ctoic** [comment]
Okay sure @YakeDev

**Comment by YakeDev** [comment]
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/bf9977b6-20f6-4919-98e4-b59dc285791f">

**Comment by YakeDev** [comment]
![image](https://github.com/user-attachments/assets/d80c4ba9-d763-4d9f-bd36-e5fbe071b38f)

**Comment by Ctoic** [comment]
Wow @YakeDev it look so amazing ❤️

**Comment by YakeDev** [comment]
Yes, little by little

**Comment by Ctoic** [comment]
I'm impressed will give you a shout out on linkedin and other platforms for your meaningfull contributions.

**Comment by YakeDev** [comment]
> I'm impressed will give you a shout out on linkedin and other platforms for your meaningfull contributions.

I'm really pleased, it's my open source project, usually I code alone on my computer; this project has helped me a lot. Thank you for giving me the chance to do something.

**Comment by Ctoic** [comment]
I love contributing and it's my 4th hactoberfest. This year i am giving chances to individuals like you who can make difference with their coding skills. @YakeDev

**Comment by YakeDev** [comment]
Thank you very much, 
Can you explain how hactoberfest works? I don't quite understand the concept.

**Comment by YakeDev** [comment]
@Ctoic
