### ISSUE TITLE
Enhance Audio Player Design

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#72]
Description: The audio player at the bottom of the page can be customized to look more cohesive with the theme of the app.
Tasks:
Redesign the audio player controls (play, pause, volume) to match the dark theme.
Make the player responsive so that it adjusts well on mobile devices.
Add a progress bar with a custom color scheme that aligns with the rest of the page.

**Comment by harshitkumargupta** [comment]
Hi @Ctoic Please assign me this issue

**Comment by swarupsahu08** [comment]
Hey @Ctoic can you pls assign me this issue

**Comment by Ctoic** [comment]
GO ahead @swarupsahu08

**Comment by dakshh-bhardwaj** [comment]
Heyy @Ctoic please assign  me this project!

**Comment by Ctoic** [comment]
It already done @dakshh-bhardwaj
