### ISSUE TITLE
Add Progress Indicator for Listening

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#73]
Description: Add a progress indicator to show how much of the book has been listened to.
Tasks:
Implement a visual bar or percentage next to each part/chapter that indicates how much of it has been played.
Store the listening progress using localStorage so users can resume where they left off.

**Comment by manoj9896** [comment]
@Ctoic  Can you please assign me this issue?

**Comment by Ctoic** [comment]
Sure @manoj9896

**Comment by manoj9896** [comment]
sharing some screenshots for review
<img width="1251" alt="Screenshot 2024-10-14 at 3 13 38 PM" src="https://github.com/user-attachments/assets/10d2a6d8-8f5d-4f59-a982-9054152f1910">
<img width="1251" alt="Screenshot 2024-10-14 at 3 13 53 PM" src="https://github.com/user-attachments/assets/27e393a6-acd9-4cd7-83aa-fc341f5fe448">

**Comment by Ctoic** [comment]
@manoj9896 perfect if you have the latest code you can create a pull reques and apply this to all the books.

**Comment by dakshh-bhardwaj** [comment]
heyy @Ctoic please assign me this issue.

**Comment by manoj9896** [comment]
@Ctoic ,
Ya I am working on it

**Comment by manoj9896** [comment]
@Ctoic I have create a pull request for this feature

**Comment by Ctoic** [comment]
Okay looks great @manoj9896

**Comment by Ctoic** [comment]
will merge it soon
