### ISSUE TITLE
Update Twitter logo

### ISSUE THREAD

**Issue by G-SaiVishwas** [Ctoic/Lisbook#76]
The logo for twitter has been updated to X due to the site's new domain "x.com". The logo has to be updated from the old logo. Please assign me this issue for Hacktoberfest 2024.

**Comment by harshitkumargupta** [comment]
Hi @Ctoic can you please assign me this

**Comment by HKSINGHTHAKUR** [comment]
Hii @Ctoic
I kindly request you to assign me this issue as a part of hactoberfest 2024
looking forward to do it

**Comment by Ctoic** [comment]
I have assigned all of you @harshitkumargupta @HKSINGHTHAKUR @G-SaiVishwas I will accept who will deliver on time with the guidence given above.
