### ISSUE TITLE
📱  Add Mobile-Friendly Menu Navigation

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#8]
Description: Currently, the app's navigation is not optimized for mobile screens. Help us improve the user experience on mobile by adding a mobile-friendly menu.

Steps to Follow:
Create a hamburger-style collapsible menu for mobile screens.
Ensure the menu works on different screen sizes (test with responsive design tools).
Make sure the mobile navigation is touch-friendly and responsive.
Add CSS animations for smooth opening/closing of the menu.

**Comment by VaradJadhav** [comment]
hey @Ctoic  please assign me this issue.
