### ISSUE TITLE
Using multiple css framework

### ISSUE THREAD

**Issue by manoj9896** [Ctoic/Lisbook#83]
Currently in the project we are using multiple css framework.
As a good practice we should use only one to avoid conflict between them.
Currently used framework.

```html

<script src="https://cdn.tailwindcss.com"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
  crossorigin="anonymous"/>
```

I will recommend using tailwind over bootstrap
@Ctoic

**Comment by manoj9896** [comment]
would like to work on this issue @Ctoic

**Comment by YakeDev** [comment]
@manoj9896 we have to remove tailwind

**Comment by Ctoic** [comment]
Yes sure @manoj9896 but we have to decide which framework we should keep. Most of the work on our site is implemented via bootsrap so we should stick to it.

**Comment by surajb0710** [comment]
@Ctoic I have already removed bootstrap and duplicate CSS code, since index.html was using tailwind, so I continued with that.
