### ISSUE TITLE
📝  Add a "Contributors" Section in README

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#9]
Description: Let’s recognize the people who contribute to LisBook! Add a section in the README to list all contributors.

Steps to Follow:
Add a "Contributors" section at the end of the README file.
Use a dynamic tool like [All Contributors](https://allcontributors.org/) or manually list contributors with GitHub profiles linked.
Include a message encouraging people to contribute.
Format the section nicely with markdown.

**Comment by VaradJadhav** [comment]
hey @Ctoic  please assign me this issue!

**Comment by Ctoic** [comment]
Okay great @VaradJadhav Best of luck and happy coding
