### ISSUE TITLE
 Add Content to the FAQ Page Following Current Website Theme

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Lisbook#99]
Description: We need to create and style a Frequently Asked Questions (FAQ) page for the LisBook website that matches the current theme and look of the app. This will help users better understand the features and usage of the app.

Tasks:

Create a new FAQ page:

The page should be consistent with the existing layout, colors, fonts, and styling of LisBook.
Add FAQ Content:

Include frequently asked questions and relevant answers about how to use LisBook (e.g., uploading audiobooks, bookmarking, sharing, etc.).
Styling:

Use the current color scheme (dark theme) and typography for the page.
Make sure the FAQ content is responsive and easy to read on both desktop and mobile devices.
Interactive FAQ Section (Optional):

Optionally, make the FAQ section interactive using JavaScript, such as collapsible answers or accordion-style sections.
Acceptance Criteria:

The FAQ page is fully designed and functional.
It follows the same theme as the rest of the website.
All the added FAQs should be informative and clear for users.
Potential Questions to Include:

How do I upload an audiobook to LisBook?
Can I listen to my audiobooks offline?
Is LisBook free to use?
How can I share an audiobook with friends?
What are the supported file formats?

**Comment by RishabhSri17** [comment]
Hey @Ctoic  I can do this task. Please can you assign it to me. Thanks!

**Comment by Ctoic** [comment]
Go ahead @RishabhSri17

**Comment by RishabhSri17** [comment]
It is already done in #107
